version: "2.2"

services:
  desktop:
    build: Desktop/
    ports:
      - "5901:5901"   # vnc
      - "6901:6901"   # noVnc
    networks:
      locale:
        ipv4_address: 172.16.1.2
  server:
    build: Server/
    tty: true        # docker run -t
    networks:
      locale:
        ipv4_address: 172.16.1.3
  lamp-server:
    build: LampServer/
    tty: true        # docker run -t
    networks:
      locale:
        ipv4_address: 172.16.1.4
networks:
  locale:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.1.0/24
