version: "2.2"

services:
  desktop:
    build: Desktop/
    privileged: true  # needed to run wireshark
    ports:
      - "6080:80"
      - "6081:443"
    networks:
      locale:
        ipv4_address: 172.16.1.2
    environment:
      - USER=user
      - PASSWORD=user
      - ALSADEV=hw:2,0
      - SSL_PORT=443
      - RELATIVE_URL_ROOT=approot
  server:
    build: Server/
    tty: true        # docker run -t
    networks:
      locale:
        ipv4_address: 172.16.1.3
  lamp-server:
    build: LampServer/
    tty: true        # docker run -t
    networks:
      locale:
        ipv4_address: 172.16.1.4
networks:
  locale:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.1.0/24
