version: "2.2"

services:
  desktop:
    image: mastrogeppetto/nglab-desktop_multiarch:latest
    container_name: desktop
    hostname: desktop
    privileged: true  # needed to run wireshark
    ports:
      - "6080:80"
    volumes:
      - ./shared:/home/user/Desktop/shared
    networks:
      locale:
        ipv4_address: 172.16.1.2
    environment:
      - USER=user
      - PASSWORD=user
      - ALSADEV=hw:2,0
      - SSL_PORT=443
      - RELATIVE_URL_ROOT=approot
  server:
    image: mastrogeppetto/nglab-server_multiarch:latest
    container_name: server
    hostname: server
    volumes:
      - ./shared:/home/user/shared
    networks:
      locale:
        ipv4_address: 172.16.1.3
  lamp-server:
    image: mastrogeppetto/nglab-lamp:stable
    container_name: lamp
    hostname: lamp
    volumes:
      - ./shared:/home/user/shared
    tty: true        # docker run -t
    networks:
      locale:
        ipv4_address: 172.16.1.4
networks:
  locale:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.1.0/24
