version: "2.2"

services:
  desktop:
    image: mastrogeppetto/nglab-desktop-arm:latest
    hostname: desktop
    privileged: true  # needed to run wireshark
    ports:
      - "6080:80"
      - "6081:443"
    networks:
      locale:
        ipv4_address: 172.16.1.2
    environment:
      - USER=user
      - PASSWORD=user
      - ALSADEV=hw:2,0
      - SSL_PORT=443
      - RELATIVE_URL_ROOT=approot
  server:
    image: mastrogeppetto/nglab-server-arm:latest
    hostname: server
    networks:
      locale:
        ipv4_address: 172.16.1.3
networks:
  locale:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.1.0/24
