version: "2.2"

services:
  desktop:
    image: mastrogeppetto/nglab-desktop_multiarch:latest
    container_name: desktop_dhcp
    hostname: desktop
    privileged: true  # needed to run wireshark
    ports:
      - "6080:80"
    volumes:
      - ./shared:/home/user/Desktop/shared
    networks:
      locale:
    environment:
      - USER=user
      - PASSWORD=user
      - ALSADEV=hw:2,0
      - SSL_PORT=443
      - RELATIVE_URL_ROOT=approot
  server:
    image: mastrogeppetto/nglab-server_multiarch:latest
    container_name: server_dhcp
    hostname: server
    volumes:
      - ./shared:/home/user/shared
    networks:
      locale:
        ipv4_address: 172.16.2.3
  lamp-server:
    image: mastrogeppetto/nglab-lamp:stable
    container_name: lamp_dhcp
    hostname: lamp
    volumes:
      - ./shared:/home/user/shared
    tty: true        # docker run -t
    networks:
      locale:
        ipv4_address: 172.16.2.4
  dhcp-server:
    image: networkboot/dhcpd
    volumes:
      - ./data:/data
    networks:
      locale:
        ipv4_address: 172.16.2.5
networks:
  locale:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.2.0/24
