version: "2.2"

services:
  desktop:
    image: mastrogeppetto/nglab-desktop_multiarch:latest
    container_name: desktop_dhcp
    hostname: desktop
    privileged: true  # needed to run wireshark
    ports:
      - "6080:80"
    volumes:
      - ./shared:/home/user/Desktop/shared
    networks:
      locale:
    environment:
      - USER=user
      - PASSWORD=user
      - ALSADEV=hw:2,0
      - SSL_PORT=443
      - RELATIVE_URL_ROOT=approot
    networks:
      locale:
        ipv4_address: 172.16.2.2
  server:
    image: mastrogeppetto/nglab-server_multiarch:latest
    container_name: server_dhcp
    hostname: server
    volumes:
      - ./shared:/home/user/shared
    networks:
      locale:
        ipv4_address: 172.16.2.3
  dhcp-server:
    image: networkboot/dhcpd
    volumes:
      - ./data:/data
    networks:
      locale:
        ipv4_address: 172.16.2.4
  webserver:
    image: httpd:2.4-alpine
    container_name: webserver
    hostname: webserver
    volumes:
      - ./public:/usr/local/apache2/htdocs/
    networks:
      locale:
        ipv4_address: 172.16.2.5
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    networks:
      locale:
        ipv4_address: 172.16.2.6
networks:
  locale:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.2.0/24
